version: '3'

networks:
  app-network:
    driver: bridge

services:
  #nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      
    networks:
      - app-network
  #php
  php:
      build:
        context: .
        dockerfile: ./php/Dockerfile
      container_name: php-container
      ports:
        - "9000:9000"
      volumes:
        - ./app:/var/www/project
      networks:
        - app-network
  #mysql
  mysql:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - app-network